import type { Metadata } from "next";

import "@/styles/globals.css";

import { sans, title } from '@/styles/fonts';
import { cn } from "@/utils";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(sans.variable, title.variable)}>{children}</body>
    </html>
  );
}
